// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwywsezbskubmgbuuewk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3eXdzZXpic2t1Ym1nYnV1ZXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTc0NDgsImV4cCI6MjA2MTczMzQ0OH0.w7vPuZ9x_usIGedOdZA2prjPGdA1ExS-n8rxMNum_yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);